// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWY1LA62yRi4enG3o4BPTbIHOJlUepybc',
    appId: '1:212178512823:web:f0f6d39b2ad2c158b15632',
    messagingSenderId: '212178512823',
    projectId: 'produk-e98d5',
    authDomain: 'produk-e98d5.firebaseapp.com',
    databaseURL: 'https://produk-e98d5-default-rtdb.firebaseio.com',
    storageBucket: 'produk-e98d5.appspot.com',
    measurementId: 'G-G3N118X9S5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_6rWeVu9hHytoae0tLbX2hz3BCYimk1I',
    appId: '1:212178512823:android:903c6a0a313d9b92b15632',
    messagingSenderId: '212178512823',
    projectId: 'produk-e98d5',
    databaseURL: 'https://produk-e98d5-default-rtdb.firebaseio.com',
    storageBucket: 'produk-e98d5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4gznIYUHBLBjhMh2eubsYfS8QvuT9UO8',
    appId: '1:212178512823:ios:c7ddb70a5685f574b15632',
    messagingSenderId: '212178512823',
    projectId: 'produk-e98d5',
    databaseURL: 'https://produk-e98d5-default-rtdb.firebaseio.com',
    storageBucket: 'produk-e98d5.appspot.com',
    iosBundleId: 'com.example.product',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4gznIYUHBLBjhMh2eubsYfS8QvuT9UO8',
    appId: '1:212178512823:ios:c7ddb70a5685f574b15632',
    messagingSenderId: '212178512823',
    projectId: 'produk-e98d5',
    databaseURL: 'https://produk-e98d5-default-rtdb.firebaseio.com',
    storageBucket: 'produk-e98d5.appspot.com',
    iosBundleId: 'com.example.product',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWY1LA62yRi4enG3o4BPTbIHOJlUepybc',
    appId: '1:212178512823:web:093fd588bb06c1ebb15632',
    messagingSenderId: '212178512823',
    projectId: 'produk-e98d5',
    authDomain: 'produk-e98d5.firebaseapp.com',
    databaseURL: 'https://produk-e98d5-default-rtdb.firebaseio.com',
    storageBucket: 'produk-e98d5.appspot.com',
    measurementId: 'G-NP6VB917S8',
  );
}
